name: spring-base

on:
  workflow_call:

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
      - name: Run unit tests
        run: ./gradlew test --no-daemon
      - name: Build application
        run: ./gradlew bootJar --no-daemon
